#!/bin/bash

    video_url="$1"
    output_dir="$2"
    shift 2

    yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 -o "${output_dir}/%(title)s.%(ext)s" "$video_url" "$@"

