#!/bin/bash

command_type="video"  # Default command type is video

# Check if the first argument is '-p'
if [ "$1" == "-p" ]; then
    command_type="playlist"
    shift  # Remove the '-p' argument
fi

if [ "$command_type" == "video" ]; then
    video_url="$1"
    output_dir="$2"
    shift 2
    yt-dlp -x --audio-format mp3 --add-metadata --embed-thumbnail -o "${output_dir}/%(title)s.%(ext)s" "$video_url" "$@"
elif [ "$command_type" == "playlist" ]; then
    playlist_url="$1"
    output_dir="$2"
    shift 2
    yt-dlp -x --audio-format mp3 --add-metadata --embed-thumbnail -o "%(title)s.%(ext)s" --yes-playlist "$playlist_url" "$@"
fi

